---
collections:
  - name: mgcdrd.infrabase
    source: https://github.com/mgcdrd/infrabase.git
    type: git
    version: v0.5.1

  - name: mgcdrd.infrasvc
    source: https://github.com/mgcdrd/infrasvc.git
    type: git
    version: v0.4.0

