---
collections:
  - name: mgcdrd.infrabase
    source: https://github.com/mgcdrd/infrabase.git
    type: git
    version: v0.16.0

  - name: mgcdrd.infrasvc
    source: https://github.com/mgcdrd/infrasvc.git
    type: git
    version: v0.11.0

