---
collections:
  - name: mgcdrd.infrabase
    source: https://github.com/mgcdrd/infrabase.git
    type: git
    version: v0.19.0

  - name: mgcdrd.infrasvc
    source: https://github.com/mgcdrd/infrasvc.git
    type: git
    version: v0.13.0

  - name: community.hashi_vault
    version: ">=6.0.0"

